/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.controllers;

import com.facebook.graph.ApiHelper;
import com.facebook.graph.AuthManager;
import com.facebook.graph.Configuration;
import com.facebook.graph.exceptions.ApiException;
import com.facebook.graph.http.Headers;
import com.facebook.graph.http.client.HttpClient;
import com.facebook.graph.http.client.HttpContext;
import com.facebook.graph.http.request.HttpRequest;
import com.facebook.graph.http.response.HttpResponse;
import com.facebook.graph.http.response.HttpStringResponse;
import com.facebook.graph.models.SetTwoStepVerificationCodeRequest;
import com.facebook.graph.models.SuccessResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/**
 * This class lists all the endpoints of the groups.
 */
public final class TwoStepVerificationController extends BaseController {

    /**
     * Initializes the controller.
     * @param config    Configurations added in client.
     * @param httpClient    Send HTTP requests and read the responses.
     * @param authManagers    Apply authorization to requests.
     */
    public TwoStepVerificationController(Configuration config, HttpClient httpClient,
            Map<String, AuthManager> authManagers) {
        super(config, httpClient, authManagers);
    }


    /**
     * You are required to set up two-step verification for your phone number, as this provides an
     * extra layer of security to the business accounts. You can use this endpoint to change
     * two-step verification code associated with your account. After you change the verification
     * code, future requests like changing the name, must use the new code. You set up two-factor
     * verification and register a phone number in the same API call.
     * @param  phoneNumberID  Required parameter: Example:
     * @param  body  Required parameter: Example:
     * @return    Returns the SuccessResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public SuccessResponse setTwoStepVerificationCode(
            final String phoneNumberID,
            final SetTwoStepVerificationCodeRequest body) throws ApiException, IOException {
        HttpRequest request = buildSetTwoStepVerificationCodeRequest(phoneNumberID, body);
        authManagers.get("global").apply(request);

        HttpResponse response = getClientInstance().execute(request, false);
        HttpContext context = new HttpContext(request, response);

        return handleSetTwoStepVerificationCodeResponse(context);
    }

    /**
     * You are required to set up two-step verification for your phone number, as this provides an
     * extra layer of security to the business accounts. You can use this endpoint to change
     * two-step verification code associated with your account. After you change the verification
     * code, future requests like changing the name, must use the new code. You set up two-factor
     * verification and register a phone number in the same API call.
     * @param  phoneNumberID  Required parameter: Example:
     * @param  body  Required parameter: Example:
     * @return    Returns the SuccessResponse response from the API call
     */
    public CompletableFuture<SuccessResponse> setTwoStepVerificationCodeAsync(
            final String phoneNumberID,
            final SetTwoStepVerificationCodeRequest body) {
        return makeHttpCallAsync(() -> buildSetTwoStepVerificationCodeRequest(phoneNumberID, body),
            req -> authManagers.get("global").applyAsync(req)
                .thenCompose(request -> getClientInstance()
                        .executeAsync(request, false)),
            context -> handleSetTwoStepVerificationCodeResponse(context));
    }

    /**
     * Builds the HttpRequest object for setTwoStepVerificationCode.
     */
    private HttpRequest buildSetTwoStepVerificationCodeRequest(
            final String phoneNumberID,
            final SetTwoStepVerificationCodeRequest body) throws JsonProcessingException {
        //the base uri for api requests
        String baseUri = config.getBaseUri();

        //prepare query string for API call
        final StringBuilder queryBuilder = new StringBuilder(baseUri
                + "/{Phone-Number-ID}");

        //process template parameters
        Map<String, SimpleEntry<Object, Boolean>> templateParameters = new HashMap<>();
        templateParameters.put("Phone-Number-ID",
                new SimpleEntry<Object, Boolean>(phoneNumberID, true));
        ApiHelper.appendUrlWithTemplateParameters(queryBuilder, templateParameters);

        //load all headers for the outgoing API request
        Headers headers = new Headers();
        headers.add("Content-Type", "application/json");
        headers.add("user-agent", BaseController.userAgent);
        headers.add("accept", "application/json");

        //prepare and invoke the API call request to fetch the response
        String bodyJson = ApiHelper.serialize(body);
        HttpRequest request = getClientInstance().postBody(queryBuilder, headers, null, bodyJson);

        return request;
    }

    /**
     * Processes the response for setTwoStepVerificationCode.
     * @return An object of type SuccessResponse
     */
    private SuccessResponse handleSetTwoStepVerificationCodeResponse(
            HttpContext context) throws ApiException, IOException {
        HttpResponse response = context.getResponse();

        //handle errors defined at the API level
        validateResponse(response, context);

        //extract result from the http response
        String responseBody = ((HttpStringResponse) response).getBody();
        SuccessResponse result = ApiHelper.deserialize(responseBody,
                SuccessResponse.class);

        return result;
    }

}