/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph;

import com.facebook.graph.controllers.BusinessProfilesController;
import com.facebook.graph.controllers.MediaController;
import com.facebook.graph.controllers.MessagesController;
import com.facebook.graph.controllers.PhoneNumbersController;
import com.facebook.graph.controllers.RegistrationController;
import com.facebook.graph.controllers.TwoStepVerificationController;
import com.facebook.graph.http.client.HttpClient;
import com.facebook.graph.http.client.HttpClientConfiguration;
import com.facebook.graph.http.client.OkClient;
import com.facebook.graph.http.client.ReadonlyHttpClientConfiguration;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;

/**
 * Gateway class for the library.
 * This class acts as a factory for Controllers.
 * It holds the state of the SDK.
 */
public final class WhatsAppCloudAPIClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private MessagesController messages;
    private RegistrationController registration;
    private BusinessProfilesController businessProfiles;
    private MediaController media;
    private PhoneNumbersController phoneNumbers;
    private TwoStepVerificationController twoStepVerification;

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * version value.
     */
    private final String version;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * BearerAuthManager.
     */
    private BearerAuthManager bearerAuthManager;

    /**
     * Map of authentication Managers.
     */
    private Map<String, AuthManager> authManagers;

    private WhatsAppCloudAPIClient(Environment environment, String version, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig, String accessToken,
            Map<String, AuthManager> authManagers) {
        this.environment = environment;
        this.version = version;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;

        this.authManagers = (authManagers == null) ? new HashMap<>() : new HashMap<>(authManagers);
        if (this.authManagers.containsKey("global")) {
            this.bearerAuthManager = (BearerAuthManager) this.authManagers.get("global");
        }

        if (!this.authManagers.containsKey("global")
                || !getBearerAuthCredentials().equals(accessToken)) {
            this.bearerAuthManager = new BearerAuthManager(accessToken);
            this.authManagers.put("global", bearerAuthManager);
        }

        messages = new MessagesController(this, this.httpClient, this.authManagers);
        registration = new RegistrationController(this, this.httpClient, this.authManagers);
        businessProfiles = new BusinessProfilesController(this, this.httpClient, this.authManagers);
        media = new MediaController(this, this.httpClient, this.authManagers);
        phoneNumbers = new PhoneNumbersController(this, this.httpClient, this.authManagers);
        twoStepVerification = new TwoStepVerificationController(this, this.httpClient,
                this.authManagers);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of MessagesController.
     * @return messages
     */
    public MessagesController getMessagesController() {
        return messages;
    }

    /**
     * Get the instance of RegistrationController.
     * @return registration
     */
    public RegistrationController getRegistrationController() {
        return registration;
    }

    /**
     * Get the instance of BusinessProfilesController.
     * @return businessProfiles
     */
    public BusinessProfilesController getBusinessProfilesController() {
        return businessProfiles;
    }

    /**
     * Get the instance of MediaController.
     * @return media
     */
    public MediaController getMediaController() {
        return media;
    }

    /**
     * Get the instance of PhoneNumbersController.
     * @return phoneNumbers
     */
    public PhoneNumbersController getPhoneNumbersController() {
        return phoneNumbers;
    }

    /**
     * Get the instance of TwoStepVerificationController.
     * @return twoStepVerification
     */
    public TwoStepVerificationController getTwoStepVerificationController() {
        return twoStepVerification;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * version value.
     * @return version
     */
    public String getVersion() {
        return version;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * The credentials to use with BearerAuth.
     * @return bearerAuthCredentials
     */
    private BearerAuthCredentials getBearerAuthCredentials() {
        return bearerAuthManager;
    }

    /**
     * OAuth 2.0 Access Token.
     * @return accessToken
     */
    public String getAccessToken() {
        return getBearerAuthCredentials().getAccessToken();
    }

    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        parameters.put("Version",
                new SimpleEntry<Object, Boolean>(this.version, false));
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }

    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://graph.facebook.com/{Version}";
            }
        }
        return "https://graph.facebook.com/{Version}";
    }

    /**
     * Converts this WhatsAppCloudAPIClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "WhatsAppCloudAPIClient [" + "environment=" + environment + ", version=" + version
                + ", httpClientConfig=" + httpClientConfig + ", authManagers=" + authManagers + "]";
    }

    /**
     * Builds a new {@link WhatsAppCloudAPIClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link WhatsAppCloudAPIClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.version = getVersion();
        builder.httpClient = getHttpClient();
        builder.accessToken = getBearerAuthCredentials().getAccessToken();
        builder.authManagers = authManagers;
        builder.httpClientConfig(configBldr -> configBldr =
                ((HttpClientConfiguration) httpClientConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link WhatsAppCloudAPIClient}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private String version = "v13.0";
        private HttpClient httpClient;
        private String accessToken = "";
        private Map<String, AuthManager> authManagers = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();


        /**
         * Credentials setter for BearerAuth.
         * @param accessToken String value for accessToken.
         * @return Builder
         */
        public Builder accessToken(String accessToken) {
            if (accessToken == null) {
                throw new NullPointerException("AccessToken cannot be null.");
            }
            this.accessToken = accessToken;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * version value.
         * @param version The version for client.
         * @return Builder
         */
        public Builder version(String version) {
            this.version = version;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Builds a new WhatsAppCloudAPIClient object using the set fields.
         * @return WhatsAppCloudAPIClient
         */
        public WhatsAppCloudAPIClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            httpClient = new OkClient(httpClientConfig);

            return new WhatsAppCloudAPIClient(environment, version, httpClient, httpClientConfig,
                    accessToken, authManagers);
        }
    }
}