/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Audio type.
 */
public class Audio {
    private String id;
    private String link;

    /**
     * Default constructor.
     */
    public Audio() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  link  String value for link.
     */
    public Audio(
            String id,
            String link) {
        this.id = id;
        this.link = link;
    }

    /**
     * Getter for Id.
     * The media object ID. Required when you are not using a link.
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * The media object ID. Required when you are not using a link.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Link.
     * The protocol and URL of the media to be sent. Use only with HTTP/HTTPS URLs. Required when
     * you are not using an uploaded media ID.
     * @return Returns the String
     */
    @JsonGetter("link")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLink() {
        return link;
    }

    /**
     * Setter for Link.
     * The protocol and URL of the media to be sent. Use only with HTTP/HTTPS URLs. Required when
     * you are not using an uploaded media ID.
     * @param link Value for String
     */
    @JsonSetter("link")
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * Converts this Audio into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Audio [" + "id=" + id + ", link=" + link + "]";
    }

    /**
     * Builds a new {@link Audio.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Audio.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .link(getLink());
        return builder;
    }

    /**
     * Class to build instances of {@link Audio}.
     */
    public static class Builder {
        private String id;
        private String link;



        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for link.
         * @param  link  String value for link.
         * @return Builder
         */
        public Builder link(String link) {
            this.link = link;
            return this;
        }

        /**
         * Builds a new {@link Audio} object using the set fields.
         * @return {@link Audio}
         */
        public Audio build() {
            return new Audio(id, link);
        }
    }
}
