/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * ButtonParameterTypeEnum to be used.
 */
public enum ButtonParameterTypeEnum {
    PAYLOAD,

    TEXT;


    private static TreeMap<String, ButtonParameterTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        PAYLOAD.value = "payload";
        TEXT.value = "text";

        valueMap.put("payload", PAYLOAD);
        valueMap.put("text", TEXT);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ButtonParameterTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ButtonParameterTypeEnum values to list of string values.
     * @param toConvert The list of ButtonParameterTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ButtonParameterTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ButtonParameterTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 