/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for EmailObject type.
 */
public class EmailObject {
    private String email;
    private PersonalInformationTypeEnum type;

    /**
     * Default constructor.
     */
    public EmailObject() {
    }

    /**
     * Initialization constructor.
     * @param  email  String value for email.
     * @param  type  PersonalInformationTypeEnum value for type.
     */
    public EmailObject(
            String email,
            PersonalInformationTypeEnum type) {
        this.email = email;
        this.type = type;
    }

    /**
     * Getter for Email.
     * @return Returns the String
     */
    @JsonGetter("email")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEmail() {
        return email;
    }

    /**
     * Setter for Email.
     * @param email Value for String
     */
    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for Type.
     * @return Returns the PersonalInformationTypeEnum
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PersonalInformationTypeEnum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for PersonalInformationTypeEnum
     */
    @JsonSetter("type")
    public void setType(PersonalInformationTypeEnum type) {
        this.type = type;
    }

    /**
     * Converts this EmailObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EmailObject [" + "email=" + email + ", type=" + type + "]";
    }

    /**
     * Builds a new {@link EmailObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EmailObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .email(getEmail())
                .type(getType());
        return builder;
    }

    /**
     * Class to build instances of {@link EmailObject}.
     */
    public static class Builder {
        private String email;
        private PersonalInformationTypeEnum type;



        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  PersonalInformationTypeEnum value for type.
         * @return Builder
         */
        public Builder type(PersonalInformationTypeEnum type) {
            this.type = type;
            return this;
        }

        /**
         * Builds a new {@link EmailObject} object using the set fields.
         * @return {@link EmailObject}
         */
        public EmailObject build() {
            return new EmailObject(email, type);
        }
    }
}
