/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for GetBusinessProfileIDResponse type.
 */
public class GetBusinessProfileIDResponse {
    private List<BusinessProfile> data;

    /**
     * Default constructor.
     */
    public GetBusinessProfileIDResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  List of BusinessProfile value for data.
     */
    public GetBusinessProfileIDResponse(
            List<BusinessProfile> data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the List of BusinessProfile
     */
    @JsonGetter("data")
    public List<BusinessProfile> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for List of BusinessProfile
     */
    @JsonSetter("data")
    public void setData(List<BusinessProfile> data) {
        this.data = data;
    }

    /**
     * Converts this GetBusinessProfileIDResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetBusinessProfileIDResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link GetBusinessProfileIDResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetBusinessProfileIDResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link GetBusinessProfileIDResponse}.
     */
    public static class Builder {
        private List<BusinessProfile> data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  List of BusinessProfile value for data.
         */
        public Builder(List<BusinessProfile> data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  List of BusinessProfile value for data.
         * @return Builder
         */
        public Builder data(List<BusinessProfile> data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link GetBusinessProfileIDResponse} object using the set fields.
         * @return {@link GetBusinessProfileIDResponse}
         */
        public GetBusinessProfileIDResponse build() {
            return new GetBusinessProfileIDResponse(data);
        }
    }
}
