/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * HeaderTypeEnum to be used.
 */
public enum HeaderTypeEnum {
    /**
     * Used for List Messages and Reply Buttons.
     */
    TEXT,

    /**
     * Used for Reply Buttons.
     */
    DOCUMENT,

    /**
     * Used for Reply Buttons.
     */
    IMAGE,

    /**
     * Used for Reply Buttons.
     */
    VIDEO;


    private static TreeMap<String, HeaderTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        TEXT.value = "text";
        DOCUMENT.value = "document";
        IMAGE.value = "image";
        VIDEO.value = "video";

        valueMap.put("text", TEXT);
        valueMap.put("document", DOCUMENT);
        valueMap.put("image", IMAGE);
        valueMap.put("video", VIDEO);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static HeaderTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of HeaderTypeEnum values to list of string values.
     * @param toConvert The list of HeaderTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<HeaderTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (HeaderTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 