/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * InteractiveTypeEnum to be used.
 */
public enum InteractiveTypeEnum {
    LIST,

    BUTTON;


    private static TreeMap<String, InteractiveTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        LIST.value = "list";
        BUTTON.value = "button";

        valueMap.put("list", LIST);
        valueMap.put("button", BUTTON);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static InteractiveTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of InteractiveTypeEnum values to list of string values.
     * @param toConvert The list of InteractiveTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<InteractiveTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (InteractiveTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 