/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Language type.
 */
public class Language {
    private String code;
    private String policy;

    /**
     * Default constructor.
     */
    public Language() {
        policy = "deterministic";
    }

    /**
     * Initialization constructor.
     * @param  code  String value for code.
     * @param  policy  String value for policy.
     */
    public Language(
            String code,
            String policy) {
        this.code = code;
        this.policy = policy;
    }

    /**
     * Getter for Code.
     * The code of the language or locale to use. Accepts both language and language_locale formats
     * (e.g., en and en_US).
     * @return Returns the String
     */
    @JsonGetter("code")
    public String getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * The code of the language or locale to use. Accepts both language and language_locale formats
     * (e.g., en and en_US).
     * @param code Value for String
     */
    @JsonSetter("code")
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for Policy.
     * The language policy the message should follow.
     * @return Returns the String
     */
    @JsonGetter("policy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPolicy() {
        return policy;
    }

    /**
     * Setter for Policy.
     * The language policy the message should follow.
     * @param policy Value for String
     */
    @JsonSetter("policy")
    public void setPolicy(String policy) {
        this.policy = policy;
    }

    /**
     * Converts this Language into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Language [" + "code=" + code + ", policy=" + policy + "]";
    }

    /**
     * Builds a new {@link Language.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Language.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(code)
                .policy(getPolicy());
        return builder;
    }

    /**
     * Class to build instances of {@link Language}.
     */
    public static class Builder {
        private String code;
        private String policy = "deterministic";

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  code  String value for code.
         */
        public Builder(String code) {
            this.code = code;
        }

        /**
         * Setter for code.
         * @param  code  String value for code.
         * @return Builder
         */
        public Builder code(String code) {
            this.code = code;
            return this;
        }

        /**
         * Setter for policy.
         * @param  policy  String value for policy.
         * @return Builder
         */
        public Builder policy(String policy) {
            this.policy = policy;
            return this;
        }

        /**
         * Builds a new {@link Language} object using the set fields.
         * @return {@link Language}
         */
        public Language build() {
            return new Language(code, policy);
        }
    }
}
