/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MarkMessageAsReadRequest type.
 */
public class MarkMessageAsReadRequest {
    private String messagingProduct;
    private String status;
    private String messageId;

    /**
     * Default constructor.
     */
    public MarkMessageAsReadRequest() {
    }

    /**
     * Initialization constructor.
     * @param  messagingProduct  String value for messagingProduct.
     * @param  status  String value for status.
     * @param  messageId  String value for messageId.
     */
    public MarkMessageAsReadRequest(
            String messagingProduct,
            String status,
            String messageId) {
        this.messagingProduct = messagingProduct;
        this.status = status;
        this.messageId = messageId;
    }

    /**
     * Getter for MessagingProduct.
     * Messaging service used for the request. Use 'whatsapp'.
     * @return Returns the String
     */
    @JsonGetter("messaging_product")
    public String getMessagingProduct() {
        return messagingProduct;
    }

    /**
     * Setter for MessagingProduct.
     * Messaging service used for the request. Use 'whatsapp'.
     * @param messagingProduct Value for String
     */
    @JsonSetter("messaging_product")
    public void setMessagingProduct(String messagingProduct) {
        this.messagingProduct = messagingProduct;
    }

    /**
     * Getter for Status.
     * A message's status. You can use this field to mark a message as read.
     * @return Returns the String
     */
    @JsonGetter("status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * A message's status. You can use this field to mark a message as read.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for MessageId.
     * Id of the incoming message.
     * @return Returns the String
     */
    @JsonGetter("message_id")
    public String getMessageId() {
        return messageId;
    }

    /**
     * Setter for MessageId.
     * Id of the incoming message.
     * @param messageId Value for String
     */
    @JsonSetter("message_id")
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    /**
     * Converts this MarkMessageAsReadRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MarkMessageAsReadRequest [" + "messagingProduct=" + messagingProduct + ", status="
                + status + ", messageId=" + messageId + "]";
    }

    /**
     * Builds a new {@link MarkMessageAsReadRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MarkMessageAsReadRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(messagingProduct, status, messageId);
        return builder;
    }

    /**
     * Class to build instances of {@link MarkMessageAsReadRequest}.
     */
    public static class Builder {
        private String messagingProduct;
        private String status;
        private String messageId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  messagingProduct  String value for messagingProduct.
         * @param  status  String value for status.
         * @param  messageId  String value for messageId.
         */
        public Builder(String messagingProduct, String status, String messageId) {
            this.messagingProduct = messagingProduct;
            this.status = status;
            this.messageId = messageId;
        }

        /**
         * Setter for messagingProduct.
         * @param  messagingProduct  String value for messagingProduct.
         * @return Builder
         */
        public Builder messagingProduct(String messagingProduct) {
            this.messagingProduct = messagingProduct;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for messageId.
         * @param  messageId  String value for messageId.
         * @return Builder
         */
        public Builder messageId(String messageId) {
            this.messageId = messageId;
            return this;
        }

        /**
         * Builds a new {@link MarkMessageAsReadRequest} object using the set fields.
         * @return {@link MarkMessageAsReadRequest}
         */
        public MarkMessageAsReadRequest build() {
            return new MarkMessageAsReadRequest(messagingProduct, status, messageId);
        }
    }
}
