/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * MessageTypeEnum to be used.
 */
public enum MessageTypeEnum {
    TEXT,

    AUDIO,

    CONTACTS,

    DOCUMENT,

    IMAGE,

    INTERACTIVE,

    LOCATION,

    STICKER,

    TEMPLATE,

    VIDEO;


    private static TreeMap<String, MessageTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        TEXT.value = "text";
        AUDIO.value = "audio";
        CONTACTS.value = "contacts";
        DOCUMENT.value = "document";
        IMAGE.value = "image";
        INTERACTIVE.value = "interactive";
        LOCATION.value = "location";
        STICKER.value = "sticker";
        TEMPLATE.value = "template";
        VIDEO.value = "video";

        valueMap.put("text", TEXT);
        valueMap.put("audio", AUDIO);
        valueMap.put("contacts", CONTACTS);
        valueMap.put("document", DOCUMENT);
        valueMap.put("image", IMAGE);
        valueMap.put("interactive", INTERACTIVE);
        valueMap.put("location", LOCATION);
        valueMap.put("sticker", STICKER);
        valueMap.put("template", TEMPLATE);
        valueMap.put("video", VIDEO);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static MessageTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of MessageTypeEnum values to list of string values.
     * @param toConvert The list of MessageTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<MessageTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (MessageTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 