/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * ParameterTypeEnum to be used.
 */
public enum ParameterTypeEnum {
    TEXT,

    CURRENCY,

    DATE_TIME,

    IMAGE,

    DOCUMENT,

    VIDEO;


    private static TreeMap<String, ParameterTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        TEXT.value = "text";
        CURRENCY.value = "currency";
        DATE_TIME.value = "date_time";
        IMAGE.value = "image";
        DOCUMENT.value = "document";
        VIDEO.value = "video";

        valueMap.put("text", TEXT);
        valueMap.put("currency", CURRENCY);
        valueMap.put("date_time", DATE_TIME);
        valueMap.put("image", IMAGE);
        valueMap.put("document", DOCUMENT);
        valueMap.put("video", VIDEO);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ParameterTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ParameterTypeEnum values to list of string values.
     * @param toConvert The list of ParameterTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ParameterTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ParameterTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 