/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * PersonalInformationTypeEnum to be used.
 */
public enum PersonalInformationTypeEnum {
    HOME,

    WORK;


    private static TreeMap<String, PersonalInformationTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        HOME.value = "HOME";
        WORK.value = "WORK";

        valueMap.put("HOME", HOME);
        valueMap.put("WORK", WORK);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static PersonalInformationTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PersonalInformationTypeEnum values to list of string values.
     * @param toConvert The list of PersonalInformationTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PersonalInformationTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PersonalInformationTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 