/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * PhoneTypeEnum to be used.
 */
public enum PhoneTypeEnum {
    HOME,

    WORK,

    CELL,

    MAIN,

    IPHONE;


    private static TreeMap<String, PhoneTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        HOME.value = "HOME";
        WORK.value = "WORK";
        CELL.value = "CELL";
        MAIN.value = "MAIN";
        IPHONE.value = "IPHONE";

        valueMap.put("HOME", HOME);
        valueMap.put("WORK", WORK);
        valueMap.put("CELL", CELL);
        valueMap.put("MAIN", MAIN);
        valueMap.put("IPHONE", IPHONE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static PhoneTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PhoneTypeEnum values to list of string values.
     * @param toConvert The list of PhoneTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PhoneTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PhoneTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 