/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * QualityRatingEnum to be used.
 */
public enum QualityRatingEnum {
    /**
     * High Quality.
     */
    GREEN,

    /**
     * Medium Quality.
     */
    YELLOW,

    /**
     * Low Quality.
     */
    RED,

    /**
     * Quality has not been determined.
     */
    NA;


    private static TreeMap<String, QualityRatingEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        GREEN.value = "GREEN";
        YELLOW.value = "YELLOW";
        RED.value = "RED";
        NA.value = "NA";

        valueMap.put("GREEN", GREEN);
        valueMap.put("YELLOW", YELLOW);
        valueMap.put("RED", RED);
        valueMap.put("NA", NA);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static QualityRatingEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of QualityRatingEnum values to list of string values.
     * @param toConvert The list of QualityRatingEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<QualityRatingEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (QualityRatingEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 