/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RegisterPhoneRequest type.
 */
public class RegisterPhoneRequest {
    private String messagingProduct;
    private String pin;

    /**
     * Default constructor.
     */
    public RegisterPhoneRequest() {
    }

    /**
     * Initialization constructor.
     * @param  messagingProduct  String value for messagingProduct.
     * @param  pin  String value for pin.
     */
    public RegisterPhoneRequest(
            String messagingProduct,
            String pin) {
        this.messagingProduct = messagingProduct;
        this.pin = pin;
    }

    /**
     * Getter for MessagingProduct.
     * Messaging service used. In this case, use "whatsapp".
     * @return Returns the String
     */
    @JsonGetter("messaging_product")
    public String getMessagingProduct() {
        return messagingProduct;
    }

    /**
     * Setter for MessagingProduct.
     * Messaging service used. In this case, use "whatsapp".
     * @param messagingProduct Value for String
     */
    @JsonSetter("messaging_product")
    public void setMessagingProduct(String messagingProduct) {
        this.messagingProduct = messagingProduct;
    }

    /**
     * Getter for Pin.
     * A 6-digit pin you have previously set up - See Set Two-Step Verification.
     * @return Returns the String
     */
    @JsonGetter("pin")
    public String getPin() {
        return pin;
    }

    /**
     * Setter for Pin.
     * A 6-digit pin you have previously set up - See Set Two-Step Verification.
     * @param pin Value for String
     */
    @JsonSetter("pin")
    public void setPin(String pin) {
        this.pin = pin;
    }

    /**
     * Converts this RegisterPhoneRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RegisterPhoneRequest [" + "messagingProduct=" + messagingProduct + ", pin=" + pin
                + "]";
    }

    /**
     * Builds a new {@link RegisterPhoneRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RegisterPhoneRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(messagingProduct, pin);
        return builder;
    }

    /**
     * Class to build instances of {@link RegisterPhoneRequest}.
     */
    public static class Builder {
        private String messagingProduct;
        private String pin;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  messagingProduct  String value for messagingProduct.
         * @param  pin  String value for pin.
         */
        public Builder(String messagingProduct, String pin) {
            this.messagingProduct = messagingProduct;
            this.pin = pin;
        }

        /**
         * Setter for messagingProduct.
         * @param  messagingProduct  String value for messagingProduct.
         * @return Builder
         */
        public Builder messagingProduct(String messagingProduct) {
            this.messagingProduct = messagingProduct;
            return this;
        }

        /**
         * Setter for pin.
         * @param  pin  String value for pin.
         * @return Builder
         */
        public Builder pin(String pin) {
            this.pin = pin;
            return this;
        }

        /**
         * Builds a new {@link RegisterPhoneRequest} object using the set fields.
         * @return {@link RegisterPhoneRequest}
         */
        public RegisterPhoneRequest build() {
            return new RegisterPhoneRequest(messagingProduct, pin);
        }
    }
}
