/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RequestVerificationCodeRequest type.
 */
public class RequestVerificationCodeRequest {
    private RequestVerificationCodeMethodEnum codeMethod;
    private String locale;

    /**
     * Default constructor.
     */
    public RequestVerificationCodeRequest() {
    }

    /**
     * Initialization constructor.
     * @param  codeMethod  RequestVerificationCodeMethodEnum value for codeMethod.
     * @param  locale  String value for locale.
     */
    public RequestVerificationCodeRequest(
            RequestVerificationCodeMethodEnum codeMethod,
            String locale) {
        this.codeMethod = codeMethod;
        this.locale = locale;
    }

    /**
     * Getter for CodeMethod.
     * Chosen method for verification.
     * @return Returns the RequestVerificationCodeMethodEnum
     */
    @JsonGetter("code_method")
    public RequestVerificationCodeMethodEnum getCodeMethod() {
        return codeMethod;
    }

    /**
     * Setter for CodeMethod.
     * Chosen method for verification.
     * @param codeMethod Value for RequestVerificationCodeMethodEnum
     */
    @JsonSetter("code_method")
    public void setCodeMethod(RequestVerificationCodeMethodEnum codeMethod) {
        this.codeMethod = codeMethod;
    }

    /**
     * Getter for Locale.
     * Your locale. For example: "en_US".
     * @return Returns the String
     */
    @JsonGetter("locale")
    public String getLocale() {
        return locale;
    }

    /**
     * Setter for Locale.
     * Your locale. For example: "en_US".
     * @param locale Value for String
     */
    @JsonSetter("locale")
    public void setLocale(String locale) {
        this.locale = locale;
    }

    /**
     * Converts this RequestVerificationCodeRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RequestVerificationCodeRequest [" + "codeMethod=" + codeMethod + ", locale="
                + locale + "]";
    }

    /**
     * Builds a new {@link RequestVerificationCodeRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RequestVerificationCodeRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(codeMethod, locale);
        return builder;
    }

    /**
     * Class to build instances of {@link RequestVerificationCodeRequest}.
     */
    public static class Builder {
        private RequestVerificationCodeMethodEnum codeMethod;
        private String locale;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  codeMethod  RequestVerificationCodeMethodEnum value for codeMethod.
         * @param  locale  String value for locale.
         */
        public Builder(RequestVerificationCodeMethodEnum codeMethod, String locale) {
            this.codeMethod = codeMethod;
            this.locale = locale;
        }

        /**
         * Setter for codeMethod.
         * @param  codeMethod  RequestVerificationCodeMethodEnum value for codeMethod.
         * @return Builder
         */
        public Builder codeMethod(RequestVerificationCodeMethodEnum codeMethod) {
            this.codeMethod = codeMethod;
            return this;
        }

        /**
         * Setter for locale.
         * @param  locale  String value for locale.
         * @return Builder
         */
        public Builder locale(String locale) {
            this.locale = locale;
            return this;
        }

        /**
         * Builds a new {@link RequestVerificationCodeRequest} object using the set fields.
         * @return {@link RequestVerificationCodeRequest}
         */
        public RequestVerificationCodeRequest build() {
            return new RequestVerificationCodeRequest(codeMethod, locale);
        }
    }
}
