/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * RequestVerificationCodeMethodEnum to be used.
 */
public enum RequestVerificationCodeMethodEnum {
    SMS,

    VOICE;


    private static TreeMap<String, RequestVerificationCodeMethodEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        SMS.value = "SMS";
        VOICE.value = "VOICE";

        valueMap.put("SMS", SMS);
        valueMap.put("VOICE", VOICE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static RequestVerificationCodeMethodEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of RequestVerificationCodeMethodEnum values to list of string values.
     * @param toConvert The list of RequestVerificationCodeMethodEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<RequestVerificationCodeMethodEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (RequestVerificationCodeMethodEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 