/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ResponseContact type.
 */
public class ResponseContact {
    private String input;
    private String waId;

    /**
     * Default constructor.
     */
    public ResponseContact() {
    }

    /**
     * Initialization constructor.
     * @param  input  String value for input.
     * @param  waId  String value for waId.
     */
    public ResponseContact(
            String input,
            String waId) {
        this.input = input;
        this.waId = waId;
    }

    /**
     * Getter for Input.
     * @return Returns the String
     */
    @JsonGetter("input")
    public String getInput() {
        return input;
    }

    /**
     * Setter for Input.
     * @param input Value for String
     */
    @JsonSetter("input")
    public void setInput(String input) {
        this.input = input;
    }

    /**
     * Getter for WaId.
     * @return Returns the String
     */
    @JsonGetter("wa_id")
    public String getWaId() {
        return waId;
    }

    /**
     * Setter for WaId.
     * @param waId Value for String
     */
    @JsonSetter("wa_id")
    public void setWaId(String waId) {
        this.waId = waId;
    }

    /**
     * Converts this ResponseContact into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResponseContact [" + "input=" + input + ", waId=" + waId + "]";
    }

    /**
     * Builds a new {@link ResponseContact.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResponseContact.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(input, waId);
        return builder;
    }

    /**
     * Class to build instances of {@link ResponseContact}.
     */
    public static class Builder {
        private String input;
        private String waId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  input  String value for input.
         * @param  waId  String value for waId.
         */
        public Builder(String input, String waId) {
            this.input = input;
            this.waId = waId;
        }

        /**
         * Setter for input.
         * @param  input  String value for input.
         * @return Builder
         */
        public Builder input(String input) {
            this.input = input;
            return this;
        }

        /**
         * Setter for waId.
         * @param  waId  String value for waId.
         * @return Builder
         */
        public Builder waId(String waId) {
            this.waId = waId;
            return this;
        }

        /**
         * Builds a new {@link ResponseContact} object using the set fields.
         * @return {@link ResponseContact}
         */
        public ResponseContact build() {
            return new ResponseContact(input, waId);
        }
    }
}
