/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RetrieveMediaURLResponse type.
 */
public class RetrieveMediaURLResponse {
    private String messagingProduct;
    private String url;
    private String mimeType;
    private String sha256;
    private String fileSize;
    private String id;

    /**
     * Default constructor.
     */
    public RetrieveMediaURLResponse() {
    }

    /**
     * Initialization constructor.
     * @param  messagingProduct  String value for messagingProduct.
     * @param  url  String value for url.
     * @param  mimeType  String value for mimeType.
     * @param  sha256  String value for sha256.
     * @param  fileSize  String value for fileSize.
     * @param  id  String value for id.
     */
    public RetrieveMediaURLResponse(
            String messagingProduct,
            String url,
            String mimeType,
            String sha256,
            String fileSize,
            String id) {
        this.messagingProduct = messagingProduct;
        this.url = url;
        this.mimeType = mimeType;
        this.sha256 = sha256;
        this.fileSize = fileSize;
        this.id = id;
    }

    /**
     * Getter for MessagingProduct.
     * @return Returns the String
     */
    @JsonGetter("messaging_product")
    public String getMessagingProduct() {
        return messagingProduct;
    }

    /**
     * Setter for MessagingProduct.
     * @param messagingProduct Value for String
     */
    @JsonSetter("messaging_product")
    public void setMessagingProduct(String messagingProduct) {
        this.messagingProduct = messagingProduct;
    }

    /**
     * Getter for Url.
     * @return Returns the String
     */
    @JsonGetter("url")
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for MimeType.
     * @return Returns the String
     */
    @JsonGetter("mime_type")
    public String getMimeType() {
        return mimeType;
    }

    /**
     * Setter for MimeType.
     * @param mimeType Value for String
     */
    @JsonSetter("mime_type")
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    /**
     * Getter for Sha256.
     * @return Returns the String
     */
    @JsonGetter("sha256")
    public String getSha256() {
        return sha256;
    }

    /**
     * Setter for Sha256.
     * @param sha256 Value for String
     */
    @JsonSetter("sha256")
    public void setSha256(String sha256) {
        this.sha256 = sha256;
    }

    /**
     * Getter for FileSize.
     * @return Returns the String
     */
    @JsonGetter("file_size")
    public String getFileSize() {
        return fileSize;
    }

    /**
     * Setter for FileSize.
     * @param fileSize Value for String
     */
    @JsonSetter("file_size")
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Converts this RetrieveMediaURLResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RetrieveMediaURLResponse [" + "messagingProduct=" + messagingProduct + ", url="
                + url + ", mimeType=" + mimeType + ", sha256=" + sha256 + ", fileSize=" + fileSize
                + ", id=" + id + "]";
    }

    /**
     * Builds a new {@link RetrieveMediaURLResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RetrieveMediaURLResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(messagingProduct, url, mimeType, sha256, fileSize, id);
        return builder;
    }

    /**
     * Class to build instances of {@link RetrieveMediaURLResponse}.
     */
    public static class Builder {
        private String messagingProduct;
        private String url;
        private String mimeType;
        private String sha256;
        private String fileSize;
        private String id;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  messagingProduct  String value for messagingProduct.
         * @param  url  String value for url.
         * @param  mimeType  String value for mimeType.
         * @param  sha256  String value for sha256.
         * @param  fileSize  String value for fileSize.
         * @param  id  String value for id.
         */
        public Builder(String messagingProduct, String url, String mimeType, String sha256,
                String fileSize, String id) {
            this.messagingProduct = messagingProduct;
            this.url = url;
            this.mimeType = mimeType;
            this.sha256 = sha256;
            this.fileSize = fileSize;
            this.id = id;
        }

        /**
         * Setter for messagingProduct.
         * @param  messagingProduct  String value for messagingProduct.
         * @return Builder
         */
        public Builder messagingProduct(String messagingProduct) {
            this.messagingProduct = messagingProduct;
            return this;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for mimeType.
         * @param  mimeType  String value for mimeType.
         * @return Builder
         */
        public Builder mimeType(String mimeType) {
            this.mimeType = mimeType;
            return this;
        }

        /**
         * Setter for sha256.
         * @param  sha256  String value for sha256.
         * @return Builder
         */
        public Builder sha256(String sha256) {
            this.sha256 = sha256;
            return this;
        }

        /**
         * Setter for fileSize.
         * @param  fileSize  String value for fileSize.
         * @return Builder
         */
        public Builder fileSize(String fileSize) {
            this.fileSize = fileSize;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Builds a new {@link RetrieveMediaURLResponse} object using the set fields.
         * @return {@link RetrieveMediaURLResponse}
         */
        public RetrieveMediaURLResponse build() {
            return new RetrieveMediaURLResponse(messagingProduct, url, mimeType, sha256, fileSize,
                    id);
        }
    }
}
