/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Row type.
 */
public class Row {
    private String id;
    private String title;
    private String description;

    /**
     * Default constructor.
     */
    public Row() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  title  String value for title.
     * @param  description  String value for description.
     */
    public Row(
            String id,
            String title,
            String description) {
        this.id = id;
        this.title = title;
        this.description = description;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Converts this Row into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Row [" + "id=" + id + ", title=" + title + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link Row.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Row.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, title)
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link Row}.
     */
    public static class Builder {
        private String id;
        private String title;
        private String description;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  title  String value for title.
         */
        public Builder(String id, String title) {
            this.id = id;
            this.title = title;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link Row} object using the set fields.
         * @return {@link Row}
         */
        public Row build() {
            return new Row(id, title, description);
        }
    }
}
