/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Section type.
 */
public class Section {
    private String title;
    private List<Row> rows;

    /**
     * Default constructor.
     */
    public Section() {
    }

    /**
     * Initialization constructor.
     * @param  title  String value for title.
     * @param  rows  List of Row value for rows.
     */
    public Section(
            String title,
            List<Row> rows) {
        this.title = title;
        this.rows = rows;
    }

    /**
     * Getter for Title.
     * Required if the message has more than one section. Title of the section.
     * @return Returns the String
     */
    @JsonGetter("title")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * Required if the message has more than one section. Title of the section.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for Rows.
     * Required for List Messages. Contains a list of rows. You can have a total of 10 rows across
     * your sections. Each row must have a title (Maximum length: 24 characters) and an ID (Maximum
     * length: 200 characters). You can add a description (Maximum length: 72 characters), but it is
     * optional.
     * @return Returns the List of Row
     */
    @JsonGetter("rows")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Row> getRows() {
        return rows;
    }

    /**
     * Setter for Rows.
     * Required for List Messages. Contains a list of rows. You can have a total of 10 rows across
     * your sections. Each row must have a title (Maximum length: 24 characters) and an ID (Maximum
     * length: 200 characters). You can add a description (Maximum length: 72 characters), but it is
     * optional.
     * @param rows Value for List of Row
     */
    @JsonSetter("rows")
    public void setRows(List<Row> rows) {
        this.rows = rows;
    }

    /**
     * Converts this Section into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Section [" + "title=" + title + ", rows=" + rows + "]";
    }

    /**
     * Builds a new {@link Section.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Section.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .title(getTitle())
                .rows(getRows());
        return builder;
    }

    /**
     * Class to build instances of {@link Section}.
     */
    public static class Builder {
        private String title;
        private List<Row> rows;



        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for rows.
         * @param  rows  List of Row value for rows.
         * @return Builder
         */
        public Builder rows(List<Row> rows) {
            this.rows = rows;
            return this;
        }

        /**
         * Builds a new {@link Section} object using the set fields.
         * @return {@link Section}
         */
        public Section build() {
            return new Section(title, rows);
        }
    }
}
