/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SetTwoStepVerificationCodeRequest type.
 */
public class SetTwoStepVerificationCodeRequest {
    private String pin;

    /**
     * Default constructor.
     */
    public SetTwoStepVerificationCodeRequest() {
    }

    /**
     * Initialization constructor.
     * @param  pin  String value for pin.
     */
    public SetTwoStepVerificationCodeRequest(
            String pin) {
        this.pin = pin;
    }

    /**
     * Getter for Pin.
     * @return Returns the String
     */
    @JsonGetter("pin")
    public String getPin() {
        return pin;
    }

    /**
     * Setter for Pin.
     * @param pin Value for String
     */
    @JsonSetter("pin")
    public void setPin(String pin) {
        this.pin = pin;
    }

    /**
     * Converts this SetTwoStepVerificationCodeRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SetTwoStepVerificationCodeRequest [" + "pin=" + pin + "]";
    }

    /**
     * Builds a new {@link SetTwoStepVerificationCodeRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SetTwoStepVerificationCodeRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(pin);
        return builder;
    }

    /**
     * Class to build instances of {@link SetTwoStepVerificationCodeRequest}.
     */
    public static class Builder {
        private String pin;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  pin  String value for pin.
         */
        public Builder(String pin) {
            this.pin = pin;
        }

        /**
         * Setter for pin.
         * @param  pin  String value for pin.
         * @return Builder
         */
        public Builder pin(String pin) {
            this.pin = pin;
            return this;
        }

        /**
         * Builds a new {@link SetTwoStepVerificationCodeRequest} object using the set fields.
         * @return {@link SetTwoStepVerificationCodeRequest}
         */
        public SetTwoStepVerificationCodeRequest build() {
            return new SetTwoStepVerificationCodeRequest(pin);
        }
    }
}
