/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SuccessResponse type.
 */
public class SuccessResponse {
    private boolean success;

    /**
     * Default constructor.
     */
    public SuccessResponse() {
    }

    /**
     * Initialization constructor.
     * @param  success  boolean value for success.
     */
    public SuccessResponse(
            boolean success) {
        this.success = success;
    }

    /**
     * Getter for Success.
     * @return Returns the boolean
     */
    @JsonGetter("success")
    public boolean getSuccess() {
        return success;
    }

    /**
     * Setter for Success.
     * @param success Value for boolean
     */
    @JsonSetter("success")
    public void setSuccess(boolean success) {
        this.success = success;
    }

    /**
     * Converts this SuccessResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SuccessResponse [" + "success=" + success + "]";
    }

    /**
     * Builds a new {@link SuccessResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SuccessResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(success);
        return builder;
    }

    /**
     * Class to build instances of {@link SuccessResponse}.
     */
    public static class Builder {
        private boolean success;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  success  boolean value for success.
         */
        public Builder(boolean success) {
            this.success = success;
        }

        /**
         * Setter for success.
         * @param  success  boolean value for success.
         * @return Builder
         */
        public Builder success(boolean success) {
            this.success = success;
            return this;
        }

        /**
         * Builds a new {@link SuccessResponse} object using the set fields.
         * @return {@link SuccessResponse}
         */
        public SuccessResponse build() {
            return new SuccessResponse(success);
        }
    }
}
