/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for UploadMediaRequest type.
 */
public class UploadMediaRequest {
    private String messagingProduct;
    private String file;
    private String type;

    /**
     * Default constructor.
     */
    public UploadMediaRequest() {
    }

    /**
     * Initialization constructor.
     * @param  messagingProduct  String value for messagingProduct.
     * @param  file  String value for file.
     * @param  type  String value for type.
     */
    public UploadMediaRequest(
            String messagingProduct,
            String file,
            String type) {
        this.messagingProduct = messagingProduct;
        this.file = file;
        this.type = type;
    }

    /**
     * Getter for MessagingProduct.
     * Messaging service used for the request. In this case, use whatsapp.
     * @return Returns the String
     */
    @JsonGetter("messaging_product")
    public String getMessagingProduct() {
        return messagingProduct;
    }

    /**
     * Setter for MessagingProduct.
     * Messaging service used for the request. In this case, use whatsapp.
     * @param messagingProduct Value for String
     */
    @JsonSetter("messaging_product")
    public void setMessagingProduct(String messagingProduct) {
        this.messagingProduct = messagingProduct;
    }

    /**
     * Getter for File.
     * Path to the file stored in your local directory. For example: "@/local/path/file.jpg".
     * @return Returns the String
     */
    @JsonGetter("file")
    public String getFile() {
        return file;
    }

    /**
     * Setter for File.
     * Path to the file stored in your local directory. For example: "@/local/path/file.jpg".
     * @param file Value for String
     */
    @JsonSetter("file")
    public void setFile(String file) {
        this.file = file;
    }

    /**
     * Getter for Type.
     * Type of media file being uploaded. See Supported Media Types for more information. Supported
     * options for images are: `image/jpeg`, `image/png` Supported options for documents are:
     * `text/plain`, `application/pdf`, `application/vnd.ms-powerpoint`, `application/msword`,
     * `application/vnd.ms-excel`,
     * `application/vnd.openxmlformats-officedocument.wordprocessingml.document`,
     * `application/vnd.openxmlformats-officedocument.presentationml.presentation`,
     * `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` Supported options for
     * audio are: `audio/aac`, `audio/mp4`, `audio/mpeg`, `audio/amr`, `audio/ogg`, `audio/opus`
     * Supported options for video are: `video/mp4`, `video/3gp` Supported options for stickers are:
     * `image/webp`
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Type of media file being uploaded. See Supported Media Types for more information. Supported
     * options for images are: `image/jpeg`, `image/png` Supported options for documents are:
     * `text/plain`, `application/pdf`, `application/vnd.ms-powerpoint`, `application/msword`,
     * `application/vnd.ms-excel`,
     * `application/vnd.openxmlformats-officedocument.wordprocessingml.document`,
     * `application/vnd.openxmlformats-officedocument.presentationml.presentation`,
     * `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` Supported options for
     * audio are: `audio/aac`, `audio/mp4`, `audio/mpeg`, `audio/amr`, `audio/ogg`, `audio/opus`
     * Supported options for video are: `video/mp4`, `video/3gp` Supported options for stickers are:
     * `image/webp`
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Converts this UploadMediaRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UploadMediaRequest [" + "messagingProduct=" + messagingProduct + ", file=" + file
                + ", type=" + type + "]";
    }

    /**
     * Builds a new {@link UploadMediaRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UploadMediaRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(messagingProduct, file, type);
        return builder;
    }

    /**
     * Class to build instances of {@link UploadMediaRequest}.
     */
    public static class Builder {
        private String messagingProduct;
        private String file;
        private String type;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  messagingProduct  String value for messagingProduct.
         * @param  file  String value for file.
         * @param  type  String value for type.
         */
        public Builder(String messagingProduct, String file, String type) {
            this.messagingProduct = messagingProduct;
            this.file = file;
            this.type = type;
        }

        /**
         * Setter for messagingProduct.
         * @param  messagingProduct  String value for messagingProduct.
         * @return Builder
         */
        public Builder messagingProduct(String messagingProduct) {
            this.messagingProduct = messagingProduct;
            return this;
        }

        /**
         * Setter for file.
         * @param  file  String value for file.
         * @return Builder
         */
        public Builder file(String file) {
            this.file = file;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Builds a new {@link UploadMediaRequest} object using the set fields.
         * @return {@link UploadMediaRequest}
         */
        public UploadMediaRequest build() {
            return new UploadMediaRequest(messagingProduct, file, type);
        }
    }
}
