/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for UrlObject type.
 */
public class UrlObject {
    private String url;
    private PersonalInformationTypeEnum type;

    /**
     * Default constructor.
     */
    public UrlObject() {
    }

    /**
     * Initialization constructor.
     * @param  url  String value for url.
     * @param  type  PersonalInformationTypeEnum value for type.
     */
    public UrlObject(
            String url,
            PersonalInformationTypeEnum type) {
        this.url = url;
        this.type = type;
    }

    /**
     * Getter for Url.
     * @return Returns the String
     */
    @JsonGetter("url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for Type.
     * @return Returns the PersonalInformationTypeEnum
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PersonalInformationTypeEnum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for PersonalInformationTypeEnum
     */
    @JsonSetter("type")
    public void setType(PersonalInformationTypeEnum type) {
        this.type = type;
    }

    /**
     * Converts this UrlObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UrlObject [" + "url=" + url + ", type=" + type + "]";
    }

    /**
     * Builds a new {@link UrlObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UrlObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .url(getUrl())
                .type(getType());
        return builder;
    }

    /**
     * Class to build instances of {@link UrlObject}.
     */
    public static class Builder {
        private String url;
        private PersonalInformationTypeEnum type;



        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  PersonalInformationTypeEnum value for type.
         * @return Builder
         */
        public Builder type(PersonalInformationTypeEnum type) {
            this.type = type;
            return this;
        }

        /**
         * Builds a new {@link UrlObject} object using the set fields.
         * @return {@link UrlObject}
         */
        public UrlObject build() {
            return new UrlObject(url, type);
        }
    }
}
