/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for VerifyCodeRequest type.
 */
public class VerifyCodeRequest {
    private String code;

    /**
     * Default constructor.
     */
    public VerifyCodeRequest() {
    }

    /**
     * Initialization constructor.
     * @param  code  String value for code.
     */
    public VerifyCodeRequest(
            String code) {
        this.code = code;
    }

    /**
     * Getter for Code.
     * The code you received after calling FROM_PHONE_NUMBER_ID/request_code.
     * @return Returns the String
     */
    @JsonGetter("code")
    public String getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * The code you received after calling FROM_PHONE_NUMBER_ID/request_code.
     * @param code Value for String
     */
    @JsonSetter("code")
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Converts this VerifyCodeRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "VerifyCodeRequest [" + "code=" + code + "]";
    }

    /**
     * Builds a new {@link VerifyCodeRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link VerifyCodeRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(code);
        return builder;
    }

    /**
     * Class to build instances of {@link VerifyCodeRequest}.
     */
    public static class Builder {
        private String code;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  code  String value for code.
         */
        public Builder(String code) {
            this.code = code;
        }

        /**
         * Setter for code.
         * @param  code  String value for code.
         * @return Builder
         */
        public Builder code(String code) {
            this.code = code;
            return this;
        }

        /**
         * Builds a new {@link VerifyCodeRequest} object using the set fields.
         * @return {@link VerifyCodeRequest}
         */
        public VerifyCodeRequest build() {
            return new VerifyCodeRequest(code);
        }
    }
}
