/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * VerticalEnum to be used.
 */
public enum VerticalEnum {
    UNDEFINED,

    OTHER,

    AUTO,

    BEAUTY,

    APPAREL,

    EDU,

    ENTERTAIN,

    EVENT_PLAN,

    FINANCE,

    GROCERY,

    GOVT,

    HOTEL,

    HEALTH,

    NONPROFIT,

    PROF_SERVICES,

    RETAIL,

    TRAVEL,

    RESTAURANT,

    NOT_A_BIZ;


    private static TreeMap<String, VerticalEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        UNDEFINED.value = "UNDEFINED";
        OTHER.value = "OTHER";
        AUTO.value = "AUTO";
        BEAUTY.value = "BEAUTY";
        APPAREL.value = "APPAREL";
        EDU.value = "EDU";
        ENTERTAIN.value = "ENTERTAIN";
        EVENT_PLAN.value = "EVENT_PLAN";
        FINANCE.value = "FINANCE";
        GROCERY.value = "GROCERY";
        GOVT.value = "GOVT";
        HOTEL.value = "HOTEL";
        HEALTH.value = "HEALTH";
        NONPROFIT.value = "NONPROFIT";
        PROF_SERVICES.value = "PROF_SERVICES";
        RETAIL.value = "RETAIL";
        TRAVEL.value = "TRAVEL";
        RESTAURANT.value = "RESTAURANT";
        NOT_A_BIZ.value = "NOT_A_BIZ";

        valueMap.put("UNDEFINED", UNDEFINED);
        valueMap.put("OTHER", OTHER);
        valueMap.put("AUTO", AUTO);
        valueMap.put("BEAUTY", BEAUTY);
        valueMap.put("APPAREL", APPAREL);
        valueMap.put("EDU", EDU);
        valueMap.put("ENTERTAIN", ENTERTAIN);
        valueMap.put("EVENT_PLAN", EVENT_PLAN);
        valueMap.put("FINANCE", FINANCE);
        valueMap.put("GROCERY", GROCERY);
        valueMap.put("GOVT", GOVT);
        valueMap.put("HOTEL", HOTEL);
        valueMap.put("HEALTH", HEALTH);
        valueMap.put("NONPROFIT", NONPROFIT);
        valueMap.put("PROF_SERVICES", PROF_SERVICES);
        valueMap.put("RETAIL", RETAIL);
        valueMap.put("TRAVEL", TRAVEL);
        valueMap.put("RESTAURANT", RESTAURANT);
        valueMap.put("NOT_A_BIZ", NOT_A_BIZ);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static VerticalEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of VerticalEnum values to list of string values.
     * @param toConvert The list of VerticalEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<VerticalEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (VerticalEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 