/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.facebook.graph.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Video type.
 */
public class Video {
    private String link;
    private String id;

    /**
     * Default constructor.
     */
    public Video() {
    }

    /**
     * Initialization constructor.
     * @param  link  String value for link.
     * @param  id  String value for id.
     */
    public Video(
            String link,
            String id) {
        this.link = link;
        this.id = id;
    }

    /**
     * Getter for Link.
     * The protocol and URL of the media to be sent. Use only with HTTP/HTTPS URLs. Required when
     * you are not using an uploaded media ID.
     * @return Returns the String
     */
    @JsonGetter("link")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLink() {
        return link;
    }

    /**
     * Setter for Link.
     * The protocol and URL of the media to be sent. Use only with HTTP/HTTPS URLs. Required when
     * you are not using an uploaded media ID.
     * @param link Value for String
     */
    @JsonSetter("link")
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * Getter for Id.
     * Required when you are not using a link. The media object ID.
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Required when you are not using a link. The media object ID.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Converts this Video into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Video [" + "link=" + link + ", id=" + id + "]";
    }

    /**
     * Builds a new {@link Video.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Video.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .link(getLink())
                .id(getId());
        return builder;
    }

    /**
     * Class to build instances of {@link Video}.
     */
    public static class Builder {
        private String link;
        private String id;



        /**
         * Setter for link.
         * @param  link  String value for link.
         * @return Builder
         */
        public Builder link(String link) {
            this.link = link;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Builds a new {@link Video} object using the set fields.
         * @return {@link Video}
         */
        public Video build() {
            return new Video(link, id);
        }
    }
}
